/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ai2313.abstractinterface640586;

/**
 *
 * @author opo25
 */
public class JInput extends javax.swing.JFrame {
     Employee em = new Employee();
     Student std = new Student();
    
    /**
     * Creates new form JInput
     */
    public JInput() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roleCB = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        codeBT = new javax.swing.JButton();
        sleepBT = new javax.swing.JButton();
        dieBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        roleCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employee", "Student" }));

        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        codeBT.setText("Code");
        codeBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeBTActionPerformed(evt);
            }
        });
        jPanel1.add(codeBT);

        sleepBT.setText("Sleep");
        sleepBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sleepBTActionPerformed(evt);
            }
        });
        jPanel1.add(sleepBT);

        dieBT.setText("Die");
        dieBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dieBTActionPerformed(evt);
            }
        });
        jPanel1.add(dieBT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roleCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roleCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codeBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeBTActionPerformed
        // TODO add your handling code here:
        if(roleCB.getSelectedIndex()==0){
           em.code();
        }else{
            std.code();
        }
    }//GEN-LAST:event_codeBTActionPerformed

    private void sleepBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sleepBTActionPerformed
        // TODO add your handling code here:
        if(roleCB.getSelectedIndex()==0){
           em.sleep();
        }else{
            std.sleep();
        }
    }//GEN-LAST:event_sleepBTActionPerformed

    private void dieBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dieBTActionPerformed
        // TODO add your handling code here:
        if(roleCB.getSelectedIndex()==0){
           em.die();
        }else{
            std.die();
        }
    }//GEN-LAST:event_dieBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JInput().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton codeBT;
    private javax.swing.JButton dieBT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> roleCB;
    private javax.swing.JButton sleepBT;
    // End of variables declaration//GEN-END:variables
}
