/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ai2313.inheritance640586;

import static java.lang.System.out;
import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author opo25
 */
public class JInput extends javax.swing.JFrame {
    CalculateSalary cal;
    int index=0;
    /**
     * Creates new form JInput
     */
    public JInput() {
        initComponents();
    }
    public JInput(CalculateSalary cal) {
        initComponents();
        this.cal=cal;
        cbPos.setSelectedItem(null);
        tfUnit.setVisible(false);
        tfUnit2.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbPos = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tfUnit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfUnit2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfSalary = new javax.swing.JTextField();
        btClear = new javax.swing.JButton();
        btSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btClose = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(7, 0, 5, 5));

        jLabel2.setText("ID");
        jPanel1.add(jLabel2);
        jPanel1.add(tfID);

        jLabel3.setText("Name");
        jPanel1.add(jLabel3);

        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });
        jPanel1.add(tfName);

        jLabel8.setText("Position");
        jPanel1.add(jLabel8);

        cbPos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sale Part-time", "Sale Full-time", "Manager", "Operator" }));
        cbPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPosActionPerformed(evt);
            }
        });
        jPanel1.add(cbPos);

        jLabel5.setText("Unit");
        jPanel1.add(jLabel5);
        jPanel1.add(tfUnit);

        jLabel6.setText("Unit2");
        jPanel1.add(jLabel6);

        tfUnit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnit2ActionPerformed(evt);
            }
        });
        jPanel1.add(tfUnit2);

        jLabel7.setText("Salary");
        jPanel1.add(jLabel7);

        tfSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSalaryActionPerformed(evt);
            }
        });
        jPanel1.add(tfSalary);

        btClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btClear.setText("Clear");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });
        jPanel1.add(btClear);

        btSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btSave.setText("Save");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btSave);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Personnel Information");

        btClose.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btClose.setText("Close");
        btClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloseActionPerformed(evt);
            }
        });

        jButton1.setText("debug");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btClose)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btClose)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        // TODO add your handling code here:
                switch(cbPos.getSelectedIndex()){
            case 0 -> {        
        PartTime pt = new PartTime(tfID.getText(),tfName.getText(),"SalePartTime",Double.parseDouble(tfSalary.getText()),Double.parseDouble(tfUnit.getText()),Double.parseDouble(tfUnit2.getText()));
        cal.setPT(pt);
            }
            case 1 -> {
        FullTime ft = new FullTime(tfID.getText(),tfName.getText(),"SaleFullTime",Double.parseDouble(tfSalary.getText()),Double.parseDouble(tfUnit.getText()),Double.parseDouble(tfUnit2.getText()));
        cal.setFT(ft);
            }
            case 2 -> {
        Manager mg = new Manager(tfID.getText(),tfName.getText(),"Manager",Double.parseDouble(tfSalary.getText()),Integer.parseInt(tfUnit.getText()));
        cal.setMG(mg);
            }
            case 3 -> {
        Operator op = new Operator(tfID.getText(),tfName.getText(),"Operator",Double.parseDouble(tfSalary.getText()),Integer.parseInt(tfUnit.getText()));
        cal.setOP(op);
            }
        }
        index++;
        


    }//GEN-LAST:event_btSaveActionPerformed

    private void btCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btCloseActionPerformed

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        // TODO add your handling code here:
        tfID.setText("");
        tfName.setText("");
        tfSalary.setText("");
        tfUnit.setText("");
        tfUnit2.setText("");
    }//GEN-LAST:event_btClearActionPerformed

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void tfUnit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnit2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnit2ActionPerformed

    private void tfSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSalaryActionPerformed

    private void cbPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPosActionPerformed
        // TODO add your handling code here:
        switch(cbPos.getSelectedIndex()){
            case 0 -> {        
                jLabel5.setText("Commission :");
                jLabel6.setText("Work Days :");
                
                tfUnit2.setVisible(true);
                jLabel6.setVisible(true);
            }
            case 1 -> {
                jLabel5.setText("Commission :");
                jLabel6.setText("Work Years :");
                tfUnit2.setVisible(true);
                jLabel6.setVisible(true);
            }
            case 2 -> {
                jLabel5.setText("Meeting Times :");
                tfUnit2.setVisible(false);
                jLabel6.setVisible(false);
            }
            case 3 -> {
                jLabel5.setText("OT Hours :");
                tfUnit2.setVisible(false);
                jLabel6.setVisible(false);
            }
        }
       tfUnit.setVisible(true);
       jLabel5.setVisible(true);
    }//GEN-LAST:event_cbPosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String out = "";
        switch(cbPos.getSelectedIndex()){
            case 0 -> {        
                out += (int) cal.getPT()[0].gettDay();
            }
            case 1 -> {
                out += (int) cal.getFT()[0].gettYear();
            }
            case 2 -> {
                out += (int) cal.getMG()[0].getSalary();
            }
            case 3 -> {
                out += (int) cal.getOP()[0].getSalary();
            }
        }
        JOptionPane.showMessageDialog(null,out);
    }//GEN-LAST:event_jButton1ActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JInput().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClear;
    private javax.swing.JButton btClose;
    private javax.swing.JButton btSave;
    private javax.swing.JComboBox<String> cbPos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfSalary;
    private javax.swing.JTextField tfUnit;
    private javax.swing.JTextField tfUnit2;
    // End of variables declaration//GEN-END:variables
}
