/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ai2313.sampleadvise;

import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author opo25
 */
public class JInput extends javax.swing.JFrame {
    
    public Advisor ads;
    /**
     * Creates new form JInput
     */
    public JInput() {
        initComponents();
    }
    public JInput(Advisor ads) {
        initComponents();
        this.ads=ads;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        advnameTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        advidTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        saveBT = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        studnameTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        studidTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        studnameTF1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        studidTF1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        studnameTF2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        studidTF2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        studCB = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        saveBT1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(2, 1, 5, 5));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Advise");
        jPanel1.add(jLabel1);
        jPanel1.add(advnameTF);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Advise id");
        jPanel1.add(jLabel2);

        advidTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advidTFActionPerformed(evt);
            }
        });
        jPanel1.add(advidTF);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Input Information");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        saveBT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        saveBT.setText("Save");
        saveBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new java.awt.GridLayout(3, 0, 5, 5));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Student 1");
        jPanel2.add(jLabel3);
        jPanel2.add(studnameTF);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Student id");
        jPanel2.add(jLabel4);

        studidTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studidTFActionPerformed(evt);
            }
        });
        jPanel2.add(studidTF);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Student 2");
        jPanel2.add(jLabel10);
        jPanel2.add(studnameTF1);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Student id");
        jPanel2.add(jLabel11);

        studidTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studidTF1ActionPerformed(evt);
            }
        });
        jPanel2.add(studidTF1);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Student 3");
        jPanel2.add(jLabel12);
        jPanel2.add(studnameTF2);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Student id");
        jPanel2.add(jLabel13);

        studidTF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studidTF2ActionPerformed(evt);
            }
        });
        jPanel2.add(studidTF2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        studCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student1 Subject", "Student2 Subject", "Student3 Subject" }));
        studCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studCBActionPerformed(evt);
            }
        });
        jPanel3.add(studCB);

        jButton2.setText("Config");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        saveBT1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        saveBT1.setText("debug");
        saveBT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBT1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 99, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(saveBT1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saveBT))
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(saveBT)
                    .addComponent(saveBT1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void advidTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advidTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_advidTFActionPerformed

    private void studidTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studidTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studidTFActionPerformed

    private void saveBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTActionPerformed
        // TODO add your handling code here:
        try{
        ads.setId(Integer.parseInt(advidTF.getText()));
        ads.setName(advnameTF.getText());
        Student stud = new Student(Integer.parseInt(studidTF.getText()),studnameTF.getText());
        Student stud2 = new Student(Integer.parseInt(studidTF1.getText()),studnameTF1.getText());
        Student stud3 = new Student(Integer.parseInt(studidTF2.getText()),studnameTF2.getText());
        ads.setStudent(stud,0);
        ads.setStudent(stud2,1);
        ads.setStudent(stud3,2);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Please complete all data");
        }
        
    }//GEN-LAST:event_saveBTActionPerformed

    private void studidTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studidTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studidTF1ActionPerformed

    private void studidTF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studidTF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studidTF2ActionPerformed

    private void studCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studCBActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new JSubject(ads.getStudent()[studCB.getSelectedIndex()]).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void saveBT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBT1ActionPerformed
        // TODO add your handling code here:
        String out;
        
        
        JOptionPane.showMessageDialog(null,"Student1 = "+ads.getGPA(0)+"\n"+"Student2 = "+ads.getGPA(1)+"\n"+"Student3 = "+ads.getGPA(2)+"\n");
    }//GEN-LAST:event_saveBT1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JInput().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField advidTF;
    private javax.swing.JTextField advnameTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton saveBT;
    private javax.swing.JButton saveBT1;
    private javax.swing.JComboBox<String> studCB;
    private javax.swing.JTextField studidTF;
    private javax.swing.JTextField studidTF1;
    private javax.swing.JTextField studidTF2;
    private javax.swing.JTextField studnameTF;
    private javax.swing.JTextField studnameTF1;
    private javax.swing.JTextField studnameTF2;
    // End of variables declaration//GEN-END:variables
}
